module Apidae
  LOCALE_FR = 'fr'
  LOCALE_EN = 'en'
  LOCALE_IT = 'it'
  LOCALE_DE = 'de'
  LOCALE_NL = 'nl'
  LOCALE_RU = 'ru'
  LOCALE_ZH = 'zh'
  LOCALE_PT_BR = 'pt-BR'

  DEFAULT_LOCALE = LOCALE_FR
  ALL_LOCALES = [LOCALE_FR, LOCALE_EN, LOCALE_IT, LOCALE_DE, LOCALE_NL, LOCALE_RU, LOCALE_ZH, LOCALE_PT_BR]
end
